services:

  web:
    image: nginx:alpine
    container_name: nginx
    volumes: 
    - "/home/vagrant/etc/nginx.conf:/etc/nginx/conf.d/default.conf"
    - "/home/vagrant/etc:/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - webapp
    deploy:
      update_config:
        failure_action: rollback

  
  php:
    image: php82fpm:latest
    container_name: php82fpm
    restart: always
    volumes:
      - "/home/vagrant/etc:/usr/share/nginx/html"
    ports:
      - "9000:9000"
    networks:
      - webapp
    deploy:
      update_config:
        failure_action: rollback

  mysql:
    image: mysql:9.0
    container_name: mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - "/home/vagrant/etc/mysql-data:/var/lib/mysql"
    networks:
      - webapp
    deploy:
      update_config:
        failure_action: rollback

networks:
  webapp:
    driver: bridge
